#!/usr/bin/env php
<?php

include 'vendor/autoload.php';

use franzliedke\ArrayShortener\ShortenCommand;
use franzliedke\ArrayShortener\Shortener;
use Symfony\Component\Console\Application;

$shortener = new Shortener;

$command = new ShortenCommand;
$command->setShortener($shortener);

$application = new Application();
$application->add($command);
$application->run();
